name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CADDY_VERSION: 2.7.5

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg CADDY_VERSION=${CADDY_VERSION} --tag caddy-cloudflaredns:$CADDY_VERSION
