on: [push]

jobs:
  build_image:
    runs-on: ubuntu-latest
    name: This job builds a Caddy server Docker image.
    steps:
      - name: Build steps
        id: build
        uses: gk-codes/docker-caddy-cloudflare@v1
        with:
          version: '2.7.5'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.build.outputs.time }}"
